[window]
dimensions            = { columns = 500, lines = 80 }
position              = { x = 0, y = 0 }
opacity               = 0.95
blur                  = false
option_as_alt         = "Both"
decorations           = "None"

[env]
TERM                  = "xterm-256color"

[scrolling]
history               = 65535
multiplier            = 3

[bell]
animation             = "EaseOutExpo"
duration              = 0
color                 = "#C0C5CE"
command               = { program = "notify-send", args = ["alacritty", "bell",] }

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[cursor.style]
shape                 = "Block"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Beam"
blinking              = "Always"

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[font]
normal                = { family = "DejaVuSansM Nerd Font Propo", style = "Regular" }
bold                  = { family = "DejaVuSansM Nerd Font Propo", style = "Bold" }
italic                = { family = "DejaVuSansM Nerd Font Propo", style = "Italic" }
bold_italic           = { family = "DejaVuSansM Nerd Font Propo", style = "Bold Italic" }
#size                  = 11.25
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'


[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
  { key = "Return",   mods = "Command",       action = "ToggleSimpleFullScreen" },
]


