# catpuccin-mocha, ported from .yml
[colors.primary]
background            = "#000000"
foreground            = "#ababab"
dim_foreground        = "#ababab"
bright_foreground     = "#ababab"

[colors.cursor]
text                  = "#000000"
cursor                = "#ababab"

[colors.vi_mode_cursor]
text                  = "#1E1E2E"
cursor                = "#B4BEFE"

[colors.search.matches]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.search.focused_match]
foreground            = "#1E1E2E"
background            = "#A6E3A1"

[colors.hints.start]
foreground            = "#1E1E2E"
background            = "#F9E2AF"

[colors.hints.end]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.line_indicator]
#foreground            = "None"
#background            = "None"

[colors.footer_bar]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.selection]
text                  = "#1E1E2E"
background            = "#F5E0DC"

[colors.normal]
black                 = "#000000"
red                   = "#e92f2f"
green                 = "#0ed839"
yellow                = "#dddd13"
blue                  = "#3b48e3"
magenta               = "#f996e2"
cyan                  = "#23edda"
white                 = "#ababab"

[colors.bright]
black                 = "#343434"
red                   = "#e92f2f"
green                 = "#0ed839"
yellow                = "#dddd13"
blue                  = "#3b48e3"
magenta               = "#f996e2"
cyan                  = "#23edda"
white                 = "#f9f9f9"

[colors.dim]
black                 = "#45475A"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#BAC2DE"

[colors]
indexed_colors = [
  { index = 16, color = "#FAB387" },
  { index = 17, color = "#F5E0DC" },
]
#transparent_background_colors = false
draw_bold_text_with_bright_colors = true


